name: CI Build & (simulate) Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t varun/flask-demo:${{ github.sha }} .

      - name: Run tests (simulated)
        run: |
          echo "Running tests..."
          echo "Tests passed"

      # Optional: Push to DockerHub (commented - requires secrets)
      #- name: Login to DockerHub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Push image
      #  run: |
      #    docker tag varun/flask-demo:${{ github.sha }} varun/flask-demo:latest
      #    docker push varun/flask-demo:latest

